language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
script:
- pytest --cov=tregex tregex
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eom528kuZpk7Y6ZbuQHZ2N1Rc+EI4JuONVsFTDWCGHFx6jsjZxvUuMMPpkZJJDftcNUKoKEzPpVhSkzjY+k8FChtiUHP5XOTde/OUlXk67Wzl3AIQAbIEod7bctxIE3O8ZushZxRAlB0LGtIxJ0VyVQ7sodme0+BNhys4MRskkdK51YqUpdaqdLxtB3432HGFRrt9/3p2PMlRokVdY7+EzCJ7ynRYeP4K91lfa7r72JZ6p0XBHtfEnPdl3AsKypAfoXYbOtawU5hQhC08BZRF7ISg2ME3Chtm8ckcIKQwuslBzEFhpAD3PI3S732bTKA7tpmGYvpyoeTw6PGuowSMEkc8TmccWj1+rdrQeUaVCnCJY3z0LjGtue5DN0WreBSYWPI3OvyS6aJdYFG09/sTgg0xjxQ17C5xYGJXZvBYK1IXh8CKUPe5UykBFv2Bod1MYUrb4uacM4rLp2QZ1h6VMuJpcLzBWepEN6sZt6fPhXq+dLl8ebQwtNoRVhEepHI86sBpRYQIYxVUnRnSXgfr3QRnuBt1LNS2ToxPfc6OuLpyHHKFkKZzWNlCaVtzXjq8GH+BjyozvPbXkl9l0juSM4bkTTw+qNnmrD/I7ISJ1Tnei/BkWhsfMbFxCmFR1eOON295cyK94Q8V1UFqT5jkxe0H7sKwInHGXyLr/DkWus=
  on:
    branch: master
  skip_existing: true
